package br.unip.cc.aps.view;

import br.unip.cc.aps.app.Aplicativo;
import br.unip.cc.aps.dao.DaoException;
import br.unip.cc.aps.model.ControladorDeJogo;
import br.unip.cc.aps.model.TipoMaterial;
import java.util.logging.Level;
import java.util.logging.Logger;

    
public class PainelBotoesLixeira extends javax.swing.JPanel {

    /**
     * Creates new form BotoesLixeira
     */
    public PainelBotoesLixeira() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlastico = new javax.swing.JButton();
        btnMetal = new javax.swing.JButton();
        btnVidro = new javax.swing.JButton();
        btnPapel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        lblLixeiraSelecionada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLixeiraSelecionada = new javax.swing.JTextPane();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setForeground(new java.awt.Color(255, 0, 0));
        setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        setFocusable(false);
        setRequestFocusEnabled(false);

        btnPlastico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unip/cc/aps/images/PLASTICO_P.png"))); // NOI18N
        btnPlastico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlastico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPlastico.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnPlastico.setDefaultCapable(false);
        btnPlastico.setFocusCycleRoot(true);
        btnPlastico.setSelected(true);
        btnPlastico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlasticoActionPerformed(evt);
            }
        });

        btnMetal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unip/cc/aps/images/METAL_P.png"))); // NOI18N
        btnMetal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMetal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMetal.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnMetal.setDefaultCapable(false);
        btnMetal.setFocusCycleRoot(true);
        btnMetal.setSelected(true);
        btnMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetalActionPerformed(evt);
            }
        });

        btnVidro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unip/cc/aps/images/VIDRO_P.png"))); // NOI18N
        btnVidro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVidro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVidro.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnVidro.setDefaultCapable(false);
        btnVidro.setFocusCycleRoot(true);
        btnVidro.setMargin(null);
        btnVidro.setSelected(true);
        btnVidro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVidroActionPerformed(evt);
            }
        });

        btnPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unip/cc/aps/images/PAPEL_P.png"))); // NOI18N
        btnPapel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPapel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPapel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnPapel.setDefaultCapable(false);
        btnPapel.setFocusCycleRoot(true);
        btnPapel.setSelected(true);
        btnPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapelActionPerformed(evt);
            }
        });

        btnOk.setText("Confirmar");
        btnOk.setToolTipText("");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        lblLixeiraSelecionada.setText("Lixeira Selecionada:");

        txtLixeiraSelecionada.setEditable(false);
        jScrollPane1.setViewportView(txtLixeiraSelecionada);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLixeiraSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnPlastico)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnVidro)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMetal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPapel)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLixeiraSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMetal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlastico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVidro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        txtLixeiraSelecionada.setText(" ");
        try {
            ControladorDeJogo.getInstance().VerificarSeAcertou();
        } catch (DaoException ex) {
            Logger.getLogger(PainelBotoesLixeira.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetalActionPerformed
        ControladorDeJogo.getInstance().setTipoBotao(TipoMaterial.METAL);
        txtLixeiraSelecionada.setText("AMARELA");
    }//GEN-LAST:event_btnMetalActionPerformed

    private void btnPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPapelActionPerformed
        ControladorDeJogo.getInstance().setTipoBotao(TipoMaterial.PAPEL);
        txtLixeiraSelecionada.setText("AZUL");
    }//GEN-LAST:event_btnPapelActionPerformed

    private void btnVidroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVidroActionPerformed
        ControladorDeJogo.getInstance().setTipoBotao(TipoMaterial.VIDRO);
        txtLixeiraSelecionada.setText("VERDE");
    }//GEN-LAST:event_btnVidroActionPerformed

    private void btnPlasticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlasticoActionPerformed
        ControladorDeJogo.getInstance().setTipoBotao(TipoMaterial.PLASTICO);
        txtLixeiraSelecionada.setText("VERMELHA");
    }//GEN-LAST:event_btnPlasticoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMetal;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPapel;
    private javax.swing.JButton btnPlastico;
    private javax.swing.JButton btnVidro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLixeiraSelecionada;
    private javax.swing.JTextPane txtLixeiraSelecionada;
    // End of variables declaration//GEN-END:variables
}
